export const currencyVals = [
  { label: 'USD', value: { val: '0.30', symbol: '$' } },
  { label: 'AUD', value: { val: '0.30', symbol: '$' } },
  { label: 'GPB', value: { val: '0.30', symbol: '£' } },
  { label: 'EUR', value: { val: '0.35', symbol: '€' } },
  { label: 'CAD', value: { val: '0.30', symbol: '$' } },
  { label: 'NZD', value: { val: '0.45', symbol: '$' } },
  { label: 'BRL', value: { val: '0.6', symbol: 'R$' } },
  { label: 'INR', value: { val: '0.30', symbol: '₹' } },
  { label: 'HKD', value: { val: '2.35', symbol: '$' } },
  { label: 'HUF', value: { val: '90', symbol: 'Ft' } },
  { label: 'ILS', value: { val: '1.2', symbol: '₪' } },
  { label: 'JPY', value: { val: '40', symbol: '￥' } },
  { label: 'MYR', value: { val: '2', symbol: 'RM' } },
  { label: 'MXN', value: { val: '4', symbol: '$' } },
  { label: 'CZK', value: { val: '10', symbol: 'Kč' } },
  { label: 'NOK', value: { val: '2.8', symbol: 'kr' } },
  { label: 'PHP', value: { val: '15', symbol: 'P' } },
  { label: 'PLN', value: { val: '1.35', symbol: 'zł' } },
  { label: 'RUB', value: { val: '10', symbol: '₽.' } },
  { label: 'SGD', value: { val: '0.5', symbol: '$' } },
  { label: 'SEK', value: { val: '3.25', symbol: 'kr' } },
  { label: 'DKK', value: { val: '2.6', symbol: 'kr' } },
  { label: 'TWD', value: { val: '10', symbol: 'NT$' } },
  { label: 'THB', value: { val: '11', symbol: '฿' } }
]

// const countryVals = [
//   { label: 'United States', value: '2.9' },
//   { label: 'United Kingdom', value: '4.4' },
//   { label: 'United States Minor Outlying Islands', value: '4.4' },
//   { label: 'Afghanistan', value: '4.4' },
//   { label: 'Land Islands', value: '4.4' },
//   { label: 'Albania', value: '4.4' },
//   { label: 'Algeria', value: '4.4' },
//   { label: 'American Samoa', value: '4.4' },
//   { label: 'AndorrA', value: '4.4' },
//   { label: 'Angola', value: '4.4' },
//   { label: 'Anguilla', value: '4.4' },
//   { label: 'Antarctica', value: '4.4' },
//   { label: 'Antigua and Barbuda', value: '4.4' },
//   { label: 'Argentina', value: '4.4' },
//   { label: 'Armenia', value: '4.4' },
//   { label: 'Aruba', value: '4.4' },
//   { label: 'Australia', value: '4.4' },
//   { label: 'Austria', value: '4.4' },
//   { label: 'Azerbaijan', value: '4.4' },
//   { label: 'Bahamas', value: '4.4' },
//   { label: 'Bahrain', value: '4.4' },
//   { label: 'Bangladesh', value: '4.4' },
//   { label: 'Barbados', value: '4.4' },
//   { label: 'Belarus', value: '4.4' },
//   { label: 'Belgium', value: '4.4' },
//   { label: 'Belize', value: '4.4' },
//   { label: 'Benin', value: '4.4' },
//   { label: 'Bermuda', value: '4.4' },
//   { label: 'Bhutan', value: '4.4' },
//   { label: 'Bolivia', value: '4.4' },
//   { label: 'Bosnia and Herzegovina', value: '4.4' },
//   { label: 'Botswana', value: '4.4' },
//   { label: 'Bouvet Island', value: '4.4' },
//   { label: 'Brazil', value: '4.4' },
//   { label: 'British Indian Ocean Territory', value: '4.4' },
//   { label: 'Brunei Darussalam', value: '4.4' },
//   { label: 'Bulgaria', value: '4.4' },
//   { label: 'Burkina Faso', value: '4.4' },
//   { label: 'Burundi', value: '4.4' },
//   { label: 'Cambodia', value: '4.4' },
//   { label: 'Cameroon', value: '4.4' },
//   { label: 'Canada', value: '4.4' },
//   { label: 'Cape Verde', value: '4.4' },
//   { label: 'Cayman Islands', value: '4.4' },
//   { label: 'Central African Republic', value: '4.4' },
//   { label: 'Chad', value: '4.4' },
//   { label: 'Chile', value: '4.4' },
//   { label: 'China', value: '4.4' },
//   { label: 'Christmas Island', value: '4.4' },
//   { label: 'Cocos (Keeling) Islands', value: '4.4' },
//   { label: 'Colombia', value: '4.4' },
//   { label: 'Comoros', value: '4.4' },
//   { label: 'Congo', value: '4.4' },
//   { label: 'Congo, The Democratic Republic of the', value: '4.4' },
//   { label: 'Cook Islands', value: '4.4' },
//   { label: 'Costa Rica', value: '4.4' },
//   { label: "Cote D'Ivoire", value: '4.4' },
//   { label: 'Croatia', value: '4.4' },
//   { label: 'Cuba', value: '4.4' },
//   { label: 'Cyprus', value: '4.4' },
//   { label: 'Czech Republic', value: '4.4' },
//   { label: 'Denmark', value: '4.4' },
//   { label: 'Djibouti', value: '4.4' },
//   { label: 'Dominica', value: '4.4' },
//   { label: 'Dominican Republic', value: '4.4' },
//   { label: 'Ecuador', value: '4.4' },
//   { label: 'Egypt', value: '4.4' },
//   { label: 'El Salvador', value: '4.4' },
//   { label: 'Equatorial Guinea', value: '4.4' },
//   { label: 'Eritrea', value: '4.4' },
//   { label: 'Estonia', value: '4.4' },
//   { label: 'Ethiopia', value: '4.4' },
//   { label: 'Falkland Islands (Malvinas)', value: '4.4' },
//   { label: 'Faroe Islands', value: '4.4' },
//   { label: 'Fiji', value: '4.4' },
//   { label: 'Finland', value: '4.4' },
//   { label: 'France', value: '4.4' },
//   { label: 'French Guiana', value: '4.4' },
//   { label: 'French Polynesia', value: '4.4' },
//   { label: 'French Southern Territories', value: '4.4' },
//   { label: 'Gabon', value: '4.4' },
//   { label: 'Gambia', value: '4.4' },
//   { label: 'Georgia', value: '4.4' },
//   { label: 'Germany', value: '4.4' },
//   { label: 'Ghana', value: '4.4' },
//   { label: 'Gibraltar', value: '4.4' },
//   { label: 'Greece', value: '4.4' },
//   { label: 'Greenland', value: '4.4' },
//   { label: 'Grenada', value: '4.4' },
//   { label: 'Guadeloupe', value: '4.4' },
//   { label: 'Guam', value: '4.4' },
//   { label: 'Guatemala', value: '4.4' },
//   { label: 'Guernsey', value: '4.4' },
//   { label: 'Guinea', value: '4.4' },
//   { label: 'Guinea-Bissau', value: '4.4' },
//   { label: 'Guyana', value: '4.4' },
//   { label: 'Haiti', value: '4.4' },
//   { label: 'Heard Island and Mcdonald Islands', value: '4.4' },
//   { label: 'Holy See (Vatican City State)', value: '4.4' },
//   { label: 'Honduras', value: '4.4' },
//   { label: 'Hong Kong', value: '4.4' },
//   { label: 'Hungary', value: '4.4' },
//   { label: 'Iceland', value: '4.4' },
//   { label: 'India', value: '4.4' },
//   { label: 'Indonesia', value: '4.4' },
//   { label: 'Iran, Islamic Republic Of', value: '4.4' },
//   { label: 'Iraq', value: '4.4' },
//   { label: 'Ireland', value: '4.4' },
//   { label: 'Isle of Man', value: '4.4' },
//   { label: 'Israel', value: '4.4' },
//   { label: 'Italy', value: '4.4' },
//   { label: 'Jamaica', value: '4.4' },
//   { label: 'Japan', value: '4.4' },
//   { label: 'Jersey', value: '4.4' },
//   { label: 'Jordan', value: '4.4' },
//   { label: 'Kazakhstan', value: '4.4' },
//   { label: 'Kenya', value: '4.4' },
//   { label: 'Kiribati', value: '4.4' },
//   { label: "Korea, Democratic People's Republic of", value: '4.4' },
//   { label: 'Korea, Republic of', value: '4.4' },
//   { label: 'Kuwait', value: '4.4' },
//   { label: 'Kyrgyzstan', value: '4.4' },
//   { label: "Lao People's Democratic Republic", value: '4.4' },
//   { label: 'Latvia', value: '4.4' },
//   { label: 'Lebanon', value: '4.4' },
//   { label: 'Lesotho', value: '4.4' },
//   { label: 'Liberia', value: '4.4' },
//   { label: 'Libyan Arab Jamahiriya', value: '4.4' },
//   { label: 'Liechtenstein', value: '4.4' },
//   { label: 'Lithuania', value: '4.4' },
//   { label: 'Luxembourg', value: '4.4' },
//   { label: 'Macao', value: '4.4' },
//   { label: 'Macedonia, The Former Yugoslav Republic of', value: '4.4' },
//   { label: 'Madagascar', value: '4.4' },
//   { label: 'Malawi', value: '4.4' },
//   { label: 'Malaysia', value: '4.4' },
//   { label: 'Maldives', value: '4.4' },
//   { label: 'Mali', value: '4.4' },
//   { label: 'Malta', value: '4.4' },
//   { label: 'Marshall Islands', value: '4.4' },
//   { label: 'Martinique', value: '4.4' },
//   { label: 'Mauritania', value: '4.4' },
//   { label: 'Mauritius', value: '4.4' },
//   { label: 'Mayotte', value: '4.4' },
//   { label: 'Mexico', value: '4.4' },
//   { label: 'Micronesia, Federated States of', value: '4.4' },
//   { label: 'Moldova, Republic of', value: '4.4' },
//   { label: 'Monaco', value: '4.4' },
//   { label: 'Mongolia', value: '4.4' },
//   { label: 'Montenegro', value: '4.4' },
//   { label: 'Montserrat', value: '4.4' },
//   { label: 'Morocco', value: '4.4' },
//   { label: 'Mozambique', value: '4.4' },
//   { label: 'Myanmar', value: '4.4' },
//   { label: 'Namibia', value: '4.4' },
//   { label: 'Nauru', value: '4.4' },
//   { label: 'Nepal', value: '4.4' },
//   { label: 'Netherlands', value: '4.4' },
//   { label: 'Netherlands Antilles', value: '4.4' },
//   { label: 'New Caledonia', value: '4.4' },
//   { label: 'New Zealand', value: '4.4' },
//   { label: 'Nicaragua', value: '4.4' },
//   { label: 'Niger', value: '4.4' },
//   { label: 'Nigeria', value: '4.4' },
//   { label: 'Niue', value: '4.4' },
//   { label: 'Norfolk Island', value: '4.4' },
//   { label: 'Northern Mariana Islands', value: '4.4' },
//   { label: 'Norway', value: '4.4' },
//   { label: 'Oman', value: '4.4' },
//   { label: 'Pakistan', value: '4.4' },
//   { label: 'Palau', value: '4.4' },
//   { label: 'Palestinian Territory, Occupied', value: '4.4' },
//   { label: 'Panama', value: '4.4' },
//   { label: 'Papua New Guinea', value: '4.4' },
//   { label: 'Paraguay', value: '4.4' },
//   { label: 'Peru', value: '4.4' },
//   { label: 'Philippines', value: '4.4' },
//   { label: 'Pitcairn', value: '4.4' },
//   { label: 'Poland', value: '4.4' },
//   { label: 'Portugal', value: '4.4' },
//   { label: 'Puerto Rico', value: '4.4' },
//   { label: 'Qatar', value: '4.4' },
//   { label: 'Reunion', value: '4.4' },
//   { label: 'Romania', value: '4.4' },
//   { label: 'Russian Federation', value: '4.4' },
//   { label: 'RWANDA', value: '4.4' },
//   { label: 'Saint Helena', value: '4.4' },
//   { label: 'Saint Kitts and Nevis', value: '4.4' },
//   { label: 'Saint Lucia', value: '4.4' },
//   { label: 'Saint Pierre and Miquelon', value: '4.4' },
//   { label: 'Saint Vincent and the Grenadines', value: '4.4' },
//   { label: 'Samoa', value: '4.4' },
//   { label: 'San Marino', value: '4.4' },
//   { label: 'Sao Tome and Principe', value: '4.4' },
//   { label: 'Saudi Arabia', value: '4.4' },
//   { label: 'Senegal', value: '4.4' },
//   { label: 'Serbia', value: '4.4' },
//   { label: 'Seychelles', value: '4.4' },
//   { label: 'Sierra Leone', value: '4.4' },
//   { label: 'Singapore', value: '4.4' },
//   { label: 'Slovakia', value: '4.4' },
//   { label: 'Slovenia', value: '4.4' },
//   { label: 'Solomon Islands', value: '4.4' },
//   { label: 'Somalia', value: '4.4' },
//   { label: 'South Africa', value: '4.4' },
//   { label: 'South Georgia and the South Sandwich Islands', value: '4.4' },
//   { label: 'Spain', value: '4.4' },
//   { label: 'Sri Lanka', value: '4.4' },
//   { label: 'Sudan', value: '4.4' },
//   { label: 'Suriname', value: '4.4' },
//   { label: 'Svalbard and Jan Mayen', value: '4.4' },
//   { label: 'Swaziland', value: '4.4' },
//   { label: 'Sweden', value: '4.4' },
//   { label: 'Switzerland', value: '4.4' },
//   { label: 'Syrian Arab Republic', value: '4.4' },
//   { label: 'Taiwan, Province of China', value: '4.4' },
//   { label: 'Tajikistan', value: '4.4' },
//   { label: 'Tanzania, United Republic of', value: '4.4' },
//   { label: 'Thailand', value: '4.4' },
//   { label: 'Timor-Leste', value: '4.4' },
//   { label: 'Togo', value: '4.4' },
//   { label: 'Tokelau', value: '4.4' },
//   { label: 'Tonga', value: '4.4' },
//   { label: 'Trinidad and Tobago', value: '4.4' },
//   { label: 'Tunisia', value: '4.4' },
//   { label: 'Turkey', value: '4.4' },
//   { label: 'Turkmenistan', value: '4.4' },
//   { label: 'Turks and Caicos Islands', value: '4.4' },
//   { label: 'Tuvalu', value: '4.4' },
//   { label: 'Uganda', value: '4.4' },
//   { label: 'Ukraine', value: '4.4' },
//   { label: 'United Arab Emirates', value: '4.4' },
//   { label: 'Uruguay', value: '4.4' },
//   { label: 'Uzbekistan', value: '4.4' },
//   { label: 'Vanuatu', value: '4.4' },
//   { label: 'Venezuela', value: '4.4' },
//   { label: 'Viet Nam', value: '4.4' },
//   { label: 'Virgin Islands, British', value: '4.4' },
//   { label: 'Virgin Islands, U.S.', value: '4.4' },
//   { label: 'Wallis and Futuna', value: '4.4' },
//   { label: 'Western Sahara', value: '4.4' },
//   { label: 'Yemen', value: '4.4' },
//   { label: 'Zambia', value: '4.4' },
//   { label: 'Zimbabwe', value: '4.4' }
// ]
export const currencies = currencyVals.map((el, i) => ({ ...el, id: i }))
// export const countries = countryVals.map((el, i) => ({ ...el, id: i }))
