export const currencyVals = [
  { label: 'USD', value: '0.30' },
  { label: 'GPB', value: '0.30' },
  { label: 'EUR', value: '0.35' },
  { label: 'CAD', value: '0.30' },
  { label: 'AUD', value: '0.30' },
  { label: 'NZD', value: '0.45' },
  { label: 'INR', value: '0.30' },
  { label: 'BRL', value: '0.6' },
  { label: 'CZK', value: '10' },
  { label: 'DKK', value: '2.6' },
  { label: 'HKD', value: '2.35' },
  { label: 'HUF', value: '90' },
  { label: 'ILS', value: '1.2' },
  { label: 'JPY', value: '40' },
  { label: 'MYR', value: '2' },
  { label: 'MXN', value: '4' },
  { label: 'TWD', value: '10' },
  { label: 'NOK', value: '2.8' },
  { label: 'PHP', value: '15' },
  { label: 'PLN', value: '1.35' },
  { label: 'RUB', value: '10' },
  { label: 'SGD', value: '0.5' },
  { label: 'SEK', value: '3.25' },
  { label: 'CHF', value: '0.55' },
  { label: 'THB', value: '11' }
]
const countryVals = [
  { label: 'United States', value: '2.9' },
  { label: 'United Kingdom', value: '2.9' },
  { label: 'Canada', value: '2.9' },
  { label: 'Australia', value: '2.6' },
  { label: 'Germany', value: '2.49' },
  { label: 'India', value: '2.5' },
  { label: 'Finland', value: '.4' },
  { label: 'Spain', value: '2.9' },
  { label: 'Denmark', value: '2.4' },
  { label: 'France', value: '0.5' },
  { label: 'Greece', value: '0.5' },
  { label: 'Greenland', value: '0.4' },
  { label: 'Iceland', value: '0.4' },
  { label: 'Norway', value: '0.4' },
  { label: 'Sweden', value: '0.4' },
  { label: 'Austria', value: '0.5' },
  { label: 'Belgium', value: '0.5' },
  { label: 'Cyprus', value: '0.5' },
  { label: 'Estonia', value: '0.5' },
  { label: 'Guadeloupe', value: '0.5' },
  { label: 'Gibraltar', value: '0.5' },
  { label: 'Ireland', value: '0.5' },
  { label: 'Italy', value: '0.5' },
  { label: 'Luxembourg', value: '0.5' },
  { label: 'Malta', value: '0.5' },
  { label: 'Montenegro', value: '0.5' },
  { label: 'Netherlands', value: '0.5' },
  { label: 'Portugal', value: '0.5' },
  { label: 'San Marino', value: '0.5' },
  { label: 'Slovakia', value: '0.5' },
  { label: 'Slovenia', value: '0.5' },
  { label: 'Vatican City State', value: '0.5' },
  { label: 'Faroe Islands', value: '0.4' },
  { label: 'Albania', value: '1.3' },
  { label: 'Andorra', value: '1.3' },
  { label: 'Belarus', value: '1.3' },
  { label: 'Bosnia', value: '1.3' },
  { label: 'Herzegovina', value: '1.3' },
  { label: 'Croatia', value: '1.3' },
  { label: 'Czech Republic', value: '1.3' },
  { label: 'Georgia', value: '1.3' },
  { label: 'Hungary', value: '1.3' },
  { label: 'Kosovo', value: '1.3' },
  { label: 'Latvia', value: '1.3' },
  { label: 'Liechtenstein', value: '1.3' },
  { label: 'Lithuania', value: '1.3' },
  { label: 'Macedonia', value: '1.3' },
  { label: 'Poland', value: '1.3' },
  { label: 'Moldova', value: '1.3' },
  { label: 'Romania', value: '1.3' },
  { label: 'Russia', value: '1.3' },
  { label: 'Serbia', value: '1.3' },
  { label: 'Switzerland', value: '1.3' },
  { label: 'Ukraine', value: '1.3' },
  { label: 'Other', value: '1.3' },
  { label: 'Albania', value: '1.3' }

]
export const currencies = currencyVals.map((el, i) => ({ ...el, id: i }))
export const countries = countryVals.map((el, i) => ({ ...el, id: i }))
